### ISSUE TITLE
Pull up the controller programmatically

### ISSUE THREAD

**Issue by Gajalakshmi94** [MarioIannotta/PullUpController#11]
How can I pull up the controller manually without any touch action?

**Comment by MarioIannotta** [comment]
From the Readme:

> It's possible to change the view controller's view position by using the method `pullUpControllerMoveToVisiblePoint(_ visiblePoint: CGFloat, completion: (() -> Void)?)`
> 
> This method will move the pull up controller's view in order to show the provided visible point.
> 
> You may use on of `pullUpControllerAllStickyPoints` item to provide a valid visible point.
> 
> visiblePoint: the y value to make visible, in screen units expressed in the pull up controller coordinate system.
> completion: The closure to execute after the animation is completed. This block has no return value and takes no parameters. You may specify nil for this parameter.

Cheers,
Mario.
