### ISSUE TITLE
Jagged, not smooth animation

### ISSUE THREAD

**Issue by ghost** [MarioIannotta/PullUpController#12]
The pullup animation seems like its going to pause at an invisible sticky point in the middle of the screen( Even though the sticky point array has only 2 points - Offset and PreferredHeight)
This makes the animation look incomplete and smooth
Any idea on how I can resolve this?

**Comment by MarioIannotta** [comment]
Hi @bhargav-hubbler,
could you please provide a simple example where I'm able to reproduce the issue?
Thank you,
Mario

**Comment by ghost** [comment]
You can see it in your demo app as well
My issue, more so of a niggle, is that the app makes a tiny laggy pull up animation, as though some sticky point exists between the Final point and Initial point
This laggy animation doesn’t happen when the gesture is continous, that is, if you were to manually drag the pullUpBar completely
This only happens when you swipe up the bar, and the pullUpView seems to not flow continuously to the top
I am unable to quite describe this as vividly as I had hoped to
Hope you understood.
Let me know if I can clarify it in any other way

**Comment by MarioIannotta** [comment]
If I understood you correctly the issue is caused by the fact that `animationDuration` in `animateLayout()` is a fixed number.
In this way if the user quickly scrolls the view the total process would appear like a two-step animation.
1. a quick animation from the current point to the pan gesture end point
2. a slow animation from the pan gesture end point to the nearest sticky point

I guess it's possible to solve the issue by changing the fixed number in something like _f(panGesture.velocity)_

@bhargav-hubbler what do you think?

**Comment by ghost** [comment]
Yeah I have tried to change the duration to something like 0.0 and 10.0 and saw the results really didn’t change
What you say makes sense and I think it correctly identifies the issue, when the user quickly scrolls the view, it appears as a 2-step animation
But the changes being made aren’t reflected the same way
So I’m wondering if the issue is caused by something else?
I will get back to you if I figure something out
Meanwhile, Thank you so much for this controller, it makes my life easier.

**Comment by MarioIannotta** [comment]
Could you please check out https://github.com/MarioIannotta/PullUpController/tree/bugfix/12-jagged-animation and see if that works for you?
Basically now the animation duration is based on the gesture recognizer pan vertical velocity (in a certain range of value).

**Comment by ghost** [comment]
Yup!
This works!
Thank you for this, helps me out a lot

**Comment by MarioIannotta** [comment]
Cool! I'll merge [bugfix/12-jagged-animation](https://github.com/MarioIannotta/PullUpController/tree/bugfix/12-jagged-animation) into develop then and release a new version in a couple of days at max.

**Comment by MarioIannotta** [comment]
The issue is solved in the [0.2.0](https://github.com/MarioIannotta/PullUpController/releases/tag/0.2.0) release.
If you're using cocoapod run a `pod update` and everything should work.
