### ISSUE TITLE
Method to remove PullUpController?

### ISSUE THREAD

**Issue by tomaculum** [MarioIannotta/PullUpController#15]
Hi,

Is there a method like the `open func addPullUpController(_ pullUpController: PullUpController)` to remove the PullUpController from the main view?

I did found the following three lines to remove a subview and added them to the `extension UIViewController` in your `PullUpController.swift` file:

```
open func removePullUpController(_ pullUpController: PullUpController) {
    pullUpController.pullUpControllerMoveToVisiblePoint(0, completion:  { () in
        pullUpController.willMove(toParentViewController: nil)
        pullUpController.view.removeFromSuperview()
        pullUpController.removeFromParentViewController()
    })
}
```

Does this make sense? Could there be a conflict with the previously added gesture recognizer or constraints?

Best,
Tom

**Comment by MarioIannotta** [comment]
Yes, it makes sense to add a method to remove the controller's view.
I've added it in https://github.com/MarioIannotta/PullUpController/commit/34da665b2ea7fcaf4df4551a5d711704cf6a6bbc along side some little minor animation improvements.
