### ISSUE TITLE
Can't find `var onDrag` in v0.3.0

### ISSUE THREAD

**Issue by andre991** [MarioIannotta/PullUpController#16]
Hello when will release the version with var "onDrag"?
Thanks.

**Comment by MarioIannotta** [comment]
Hi @andre991, are you sure you've updated the pod?
[Check this example project](https://github.com/MarioIannotta/PullUpController/files/2227749/Test.zip) - I'm using `onDrag` in `ViewController.swift` line 17.

**Comment by andre991** [comment]
Hi @MarioIannotta I saw the example but I haven't found.
<img width="514" alt="screen shot 2018-07-25 at 14 50 50" src="https://user-images.githubusercontent.com/8302454/43218427-c27bbcfc-901a-11e8-8614-a2c903e56749.png">

**Comment by MarioIannotta** [comment]
Can you please paste here the content of `Podfile.lock`?

**Comment by obianachebe** [comment]
@MarioIannotta I'm having the same issue. See pod details below

**Podfile**

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'FitGenie' do
	pod 'PullUpController'
end

**Podfile.lock**

PODS:
  - PullUpController (0.2.0)

**Comment by MarioIannotta** [comment]
@obianachebe that's because you're using the version `0.2.0`
Could you please try to run a `pod update` and paste here the result?

**Comment by obianachebe** [comment]
@MarioIannotta my mistake. All is good after updating
