### ISSUE TITLE
Update preferred height

### ISSUE THREAD

**Issue by fabiangiger** [MarioIannotta/PullUpController#18]
Would be awesome to be able to adjust the preferred height will the pull up controller is already visible.

**Comment by MarioIannotta** [comment]
Could you please checkout [`feature/resize`](https://github.com/MarioIannotta/PullUpController/tree/feature/resize) and see if that works for you? You can also try the resize with the demo project.

**Comment by MarioIannotta** [comment]
Merged in 6dca68274b7ef6f029077f85a62252b8f0dc367e
If you're using CocoaPods, please run a `pod update`.
