### ISSUE TITLE
Initial height as 0.x of Screen height and downward scrolling in Pull Up Controller and vice-versa

### ISSUE THREAD

**Issue by pratyush-techjini** [MarioIannotta/PullUpController#22]
Hi,

I have used a pull-up controller for one of my projects. I am stuck in a situation:

- When the view launches my pull up view height should be 0.6 * the screen height. 

- To achieve this I have changed the height from 50 to 0.6 * the screen height. 

- Now, my pull controller goes to the top,comes back to the given height. 

- From this height 0.6* the screen height, I want the controller to come down to the bottom and again go up to both the heights. 

I am not able to change the logic to achieve this. How can we modify the logic so that we can achieve this transformation of this order:

On launch -  0.6 * screen height
Top scroll - 400
downward scrolling - 0.6 * screen height
downward scrolling - 50 (Not able to achieve)
upward scrolling - 0.6 * screen height
upward scrolling - 400

Please help me out as I need to implement it urgently and save me from rework

**Comment by MarioIannotta** [comment]
Hi @pratyush-techjini I've just pushed some changes in [`bugfix/fix-initial-state`](https://github.com/MarioIannotta/PullUpController/tree/bugfix/fix-initial-state). 
You can achieve the effect you're talking about in the demo project by select "Expanded" as initial state and by tapping "Remove" then "Add".

You can know more on how the bug has been fixed here: https://github.com/MarioIannotta/PullUpController/commit/e52ad681ee553ca9216398ea009eb542080556e8

Let me know what do you think of the fix.

**Comment by pratyush-techjini** [comment]
Thank you @MarioIannotta
