### ISSUE TITLE
How to detect view expanded to full size

### ISSUE THREAD

**Issue by chanonly123** [MarioIannotta/PullUpController#25]
How to detect view expanded to full size? I dont want my tableView to scroll untill the View is fully expanded.

**Comment by MarioIannotta** [comment]
Hi @chanonly123 
you can just use the callbacks 
`willMoveToStickyPoint: ((_ point: CGFloat) -> Void)` or 
`didMoveToStickyPoint: ((_ point: CGFloat) -> Void)` 
and check if `point.y` is equal to `pullUpControllerAllStickyPoints.last.y`.

Let me know if that works for you.

**Comment by chanonly123** [comment]
Im using this logic, its not working as expected. Thank you for your help.

```
    override func viewDidLoad() {
        super.viewDidLoad()

        didMoveToStickyPoint = { [weak self] point in
            self?.isFull(point)
        }
        
        willMoveToStickyPoint = { [weak self] point in
            self?.isFull(point)
        }
    }
    
    func isFull(_ point: CGFloat) {
        if point != pullUpControllerAllStickyPoints.last! {
            contentVC?.tableView?.contentOffset.y = 0
        }
    }
```

**Comment by MarioIannotta** [comment]
What's exactly is not working? In my example if `point == self.pullUpControllerAllStickyPoints.last` that means that the controller's view is fully expanded. 
I'm using this code:
```
        willMoveToStickyPoint = { point in
            print("is full expanded: \(point == self.pullUpControllerAllStickyPoints.last)")
        }
```
That doesn't work for you?

**Comment by chanonly123** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13619184/45429422-e6fb3900-b6c0-11e8-80bd-ecd25a0ee820.gif)

(point == self.pullUpControllerAllStickyPoints.last) is working fine but cant stop scroll tableView

**Comment by MarioIannotta** [comment]
Ok, so the problem is not `How to detect view expanded to full size`. 
Please let's discuss the problem in detail in another issue.
Thanks,
Mario.
