### ISSUE TITLE
Does not work on iPhone XR, XS, XS Max simulator

### ISSUE THREAD

**Issue by vjdaemp** [MarioIannotta/PullUpController#28]
When running on the iPhone XR Simulator, the view controller does not "drag" up slowly when using finger like it does on iPhone 7 Simulator.

Do not have iPhone XR/XS to determine if this is a simulator issue, or issue with code.

**Comment by MarioIannotta** [comment]
Hi @vjdaemp It could be a simulator issue since on my machine everything looks good on iPhone XS and XS Max but on iPhone XR I can see the issue you mentioned. 
I'll keep the issue open until I get my hands on those devices and do a real test.

**Comment by aftabaig** [comment]
Hi @MarioIannotta 
I am having the same issues on all these simulators and even on an iPhone X simulator.

**Comment by MarioIannotta** [comment]
Hi Guys, 
I've just tried on a real iPhone XS Max and everything works fine.
[XS Max.mov.zip](https://github.com/MarioIannotta/PullUpController/files/2445335/XS.Max.mov.zip)

I'll close the issue since it's a simulator issue.
