### ISSUE TITLE
Few things to add, if possible

### ISSUE THREAD

**Issue by heltisace** [MarioIannotta/PullUpController#33]
Hi. Love you lib, though there are two things I'm concerned about:
1) Could you add some way to change animations, except for copying the file and changing them yourself? Overriding is not quite an option because not all the functions using animation are open.
2) On bounce or spring animation, I'm using now, there is some free space in the bottom when animating. It looks a bit weird. For now, I'm fixing it adding some extra height in pullUpControllerPreferredSize, though it would be also nice if you could do something with it, or at least I will be grateful if you could give me some advice how to do it better.

Thanks :)

Edit: also seems logical to call willMoveToStickyPoint and didMoveToStickyPoint on moveToVisiblePointHandling.

**Comment by MarioIannotta** [comment]
Hi @Heltisace, 
1. Could you please be more specific? What do you want to change regarding the animations? Maybe the duration? 
2. I've enabled the bounce in the demo project and can't find any free space at the bottom, maybe i misunderstood your issue?

Regarding calling `willMoveToStickyPoint` and `didMoveToStickyPoint` in `moveToVisiblePoint`, that's a good idea, thanks for pointing that out!

Cheers,
Mario

**Comment by heltisace** [comment]
1) I mean changing not only the duration but maybe the type too? For now, I had to change all the animation calls in lib to the spring animation and overriding is not quite an option, because not all the functions using animation are open. Lib with Spring animation: https://pastebin.com/VfdhjW8h. As you can see not only duration has to be changed.
2) Here's a video without Spring animation and with it. It just seems weird. I think it could be better if during bouncing the bottom will not show the main controller, but rather drawer should get bigger. 
https://drive.google.com/file/d/1jJbDJ6uoYPHHMMMFSG55hCccNMpoK7Nq/view?usp=sharing
https://drive.google.com/file/d/1Y5qf9NDXRZGCDJtCc21wUbAoB4EKlHue/view?usp=sharing

Thanks for your response :)

**Comment by MarioIannotta** [comment]
I've fixed the black space when bouncing is enabled and provided a way of customize animation in the 0.5.1 release; [more info here](https://github.com/MarioIannotta/PullUpController/releases/tag/0.5.1).
If you've installed the library through cocoapod, please run a `pod update`.

Cheers,
Mario.

**Comment by heltisace** [comment]
@MarioIannotta wow! Thanks, man. Don't want to be pushy, though I reviewed commits and didn't see you adding `willMoveToStickyPoint` and `didMoveToStickyPoint` in `moveToVisiblePoint`. If I'm wrong and just missed it, sorry. In any way, thanks again!

**Comment by MarioIannotta** [comment]
Damn, you're right, I'll open another issue so I won't forget about it.
Thanks,
Mario.

**Comment by heltisace** [comment]
@MarioIannotta thanks and sorry for making problems :D Your lib is great 👍
