### ISSUE TITLE
Call `willMoveToStickyPoint` and `didMoveToStickyPoint` in `moveToVisiblePoint`

### ISSUE THREAD

**Issue by MarioIannotta** [MarioIannotta/PullUpController#35]

**Comment by heltisace** [comment]
That's just when you call `moveToVisiblePoint` it's not quite `StickyPoint` (and closures are called `willMoveToStickyPoint` and `didMoveToStickyPoint`) and that's what may be confusing. And if this `VisiblePoint` is not `StickyPoint` does `PullUp` go to the closest `StickyPoint` or stay there even if thought logically it should not? 
Probably not quite an issue, as I've said, just my thoughts on this topic.

**Comment by MarioIannotta** [comment]
Ah I get your point now.
Let's image to have three sticky point: 10, 20 and 30, calling `pullUpControllerMoveToVisiblePoint(15, animated: true, completion: nil)` will cause `willMoveToStickyPoint` and `didMoveToStickyPoint` to be called and 15 to be passed as parameter but 15 isn't a sticky point.

I didn't thought about that because to me it doesn't really make sense to pass a "non sticky point" to that method but now there're two solution:
1. rename `willMoveToStickyPoint` and `didMoveToStickyPoint` to `willMoveToPoint` and `didMoveToPoint`
2. move the pull up controller's view to the nearest sticky point in `pullUpControllerMoveToVisiblePoint`

 I think the first solution is better, if someone wants the view to be positioned to some sticky point it could just provide it to the method. 
What do you think?

**Comment by heltisace** [comment]
I also don't move `PullUp` to any other points, though that's just what I wondered about. Yeah, the first option will provide more flexibility and will solve one side of the issue, though then you will be able to fix `PullUp` on the place where it shouldn't stay because the logic is that `PullUp` can only be fixed on sticky points.
I also don't know what solution is better, though if we look only on the library's logic `pullUpControllerMoveToVisiblePoint` should move to the nearest point, after all. 
That's nothing of critic issue in the end, so any of those solutions will pass, I think.

**Comment by Heltisace** [comment]
If someone will need it sometime, temporary for content not to scroll when not needed created a CollectionView subclass and setting its scrolling property in scrollViewWillBeginDragging.

```
//MARK: The function that is called each time user is about to scroll
    func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
        //Setting scrolling value according to opened state
        collectionView.set(scrolling: state == .open)
    }
```

```
//MARK: Custom collectin view to work with PullUp
class PullUpCollectionView: UICollectionView {
    //MARK: Variable saying if should be scrollable
    private var scrolling: Bool = false
    //MARK: Variable that saves initial content offset value
    private var initialContentOffset: CGPoint = .zero
    
    //MAKR: The function for setting if scrolling is enabled
    func set(scrolling: Bool) {
        //Setting scrolling
        self.scrolling = scrolling
        //And initial content offset
        self.initialContentOffset = contentOffset
    }
    
    //MARK: Overriding content offset
    override var contentOffset: CGPoint {
        //On set
        didSet {
            //Checking if value is not the initial and shouldn't scrolling
            if contentOffset != initialContentOffset && !scrolling {
                //Then setting value back to starter one
                contentOffset = initialContentOffset
            }
        }
    }
}
```

**Comment by MarioIannotta** [comment]
I'll go with the first solution here, since in https://github.com/MarioIannotta/PullUpController/issues/40 we talked about using function instead of callbacks the new functions will be
```swift 
pullUpControllerWillMove(to point: CGFloat)
pullUpControllerDidMove(to point: CGFloat)
pullUpControllerDidDrag(to point: CGFloat)
```
