### ISSUE TITLE
how to show  Fully popup Expand window ?

### ISSUE THREAD

**Issue by isaacraja15** [MarioIannotta/PullUpController#37]
i have one doubt in this pod, 
for eg 
if i click But ticket button how to show popup window ?

Could you give the code for this ?

For hide i use 
pullUpControllerMoveToVisiblePoint(pullUpControllerAllStickyPoints[0], animated: true, completion: nil)
this is working 

but how to show window on event ?

**Comment by MarioIannotta** [comment]
Hi @isaacraja15 everything you need has been done in the example project.
[Here is the code](https://github.com/MarioIannotta/PullUpController/blob/master/Example/PullUpController/UI/MapViewController.swift#L48) to add the controller's view.

**Comment by isaacraja15** [comment]
ya siri try this but i get all features but i need button click popup window expand fully . Im new to swift .
could you please guide me ?
i attached screen shot . if i click buy ticket button popup window will be expand .
what can i use ?
i use this -> pullUpControllerMoveToVisiblePoint(pullUpControllerAllStickyPoints[0], animated: true, completion: nil) .    for Hide That window

this for -> pullUpControllerMoveToVisiblePoint(pullUpControllerMiddleStickyPoints[0], animated: true, completion: nil) .     expand with limited size how can i write code for fully open like second screen shot 
https://www.dropbox.com/s/kn4f9qqd78st7q4/Image-1.jpg?dl=0
https://www.dropbox.com/s/u52hlbclsa6zt9y/IMG_0088.PNG?dl=0

**Comment by MarioIannotta** [comment]
It's really hard to understand what your issue is, but if I guess correctly what you need is `pullUpControllerMoveToVisiblePoint(pullUpControllerAllStickyPoints.last!, animated: true, completion: nil) `

Cheers,
Mario.

**Comment by isaacraja15** [comment]
sorry for my English Sir, Thank you so much its work.
