### ISSUE TITLE
Use function instead of closures where possible

### ISSUE THREAD

**Issue by heltisace** [MarioIannotta/PullUpController#40]
Haven't you thought about changing some closures to functions opened to overriding, so that you could make a few overrides? For example, I have a subclass of `PullUpController` `ABC`, which is superclass to another class `CDF`. To call some function from `ABC` on each call in `CDF`  I have to do something like this for now.
![image](https://user-images.githubusercontent.com/22798968/48427239-0110d080-e771-11e8-8290-9faca9603924.png)
Maybe I just don't know something.

**Comment by MarioIannotta** [comment]
Hi @Heltisace 
if I have understood right your issue, you can call the "super" of a closure with something like this:
```swift
let oldDidMoveToStickyPoint = didMoveToStickyPoint
didMoveToStickyPoint = { point in
    oldDidMoveToStickyPoint?(point) // this act like a super
    // your "new" stuff here
}
```

does that help?

**Comment by heltisace** [comment]
Hi @MarioIannotta. Actually not quite that was the problem. I would ask in another way. What if I want for some action to be performed when `didMoveToStickyPoint` or `willMoveToStickyPoint` are called, leaving a space to change them?

UPD: As I've said, I have my `custom PullController` which is a subclass of yours. And some variables are set on `didMoveToStickyPoint` or `willMoveToStickyPoint`, but those closures are also used in classes that have my `custom PullController` as the superclass, if this makes sense.

**Comment by MarioIannotta** [comment]
you could do something like:
```swift
didMoveToStickyPoint  = { point in
   someAction()
   // other stuff here
}
```
but i don't think that's you case...

let's assume we have a function `didMoveToStickyPoint(_ point: CGPoint)`, what your use case would look like?

**Comment by heltisace** [comment]
I would probably override it firstly in `CustomPullController: PullUpController` and secondly in `ABCPullController: CustomPullController` so that two actions stack.

**Comment by MarioIannotta** [comment]
ok then something like this should work:
```swift
class CustomPullController: PullUpController {

  func viewDidLoad() {
    super.viewDidLoad()
    didMoveToStickyPoint = { point in
      print("this is CustomPullController")
      // other stuff here
    }
  }

}

class ABCPullController: CustomPullController {

  func viewDidLoad() {
    super.viewDidLoad()
    let oldDidMoveToStickyPoint = didMoveToStickyPoint
    didMoveToStickyPoint = { point in
      oldDidMoveToStickyPoint?(point) // this act like a super
      print("this is ABCPullController")
    }
  }

}

```
finally when `didMoveToStickyPoint` is called in `ABCPullController` you should see in the console something like that
```
"this is CustomPullController"
"this is ABCPullController"
```

**Comment by heltisace** [comment]
That actually makes sense, though in my scenario first's controller function is more important than the second's, so it's more important for the first function to always be called. And if anyone else will have my code after me, they can just forget to call the old value or something. Simply saying, do you think it's transparent enough and logically in terms of task prioritization? We have some subclass having control upon its superclass's obligatory features.

UPD: The only thing that I mean, that even in the current variant only thing user of `CustomPullController` has to do is just to set a new value to `didMoveToStickyPoint` and both actions would be performed. No misunderstood and no chance to lose anything. With functions it could be more transparent. Though I'm quite fine like it is, if you think that closures are a better way to tansmit information.

**Comment by heltisace** [comment]
Here's a code how it can be done now:
```swift
class CustomPullController: PullUpController {
    //MARK: Variable showing if super closures were already reset
    private var closureConfigured: Bool = false
    //MARK: Closure that is called when did move to a sticky point
    override var didMoveToStickyPoint: ((CGFloat) -> Void)? {
        //On each set
        didSet {
            //Checking for closure was not configured yet
            guard !closureConfigured else {
                //If was -> reseting variable
                closureConfigured = false
                return
            }
            //Setting configures to true
            closureConfigured = true
            //Reseting to such so
            didMoveToStickyPoint = { point in
                //Setting active state
                print("Important")
                //Calling previous version of this function
                oldValue?(point)
            }
        }
    }
}

class ABCPullController: CustomPullController {
    override func viewDidLoad() {
        super.viewDidLoad()
        didMoveToStickyPoint = { _ in
            print("Not that important")
        }
    }
}
```
And we must get:
```
Important
Not that important
```
If I didn't miss anything, was writing code right there :)

UPD: I did miss a lot of things :<

**Comment by MarioIannotta** [comment]
Ok, I get your point.
I'll change the closure to function to make everything more transparent and more iOS-SDK like.

The new functions will be 
```swift
pullUpControllerWillMove(to stickyPoint: CGFloat)
pullUpControllerDidMove(to stickyPoint: CGFloat)
pullUpControllerDidDrag(to point: CGFloat)
```
