### ISSUE TITLE
How to increase the visible point height 

### ISSUE THREAD

**Issue by Confidexuta** [MarioIannotta/PullUpController#41]
With the latest pod update I cannot increase the visible point height.  Previosuly I was able to increase with increasing previewOffsetValue. Now it has been removed. 

 ```
override var pullUpControllerPreviewOffset: CGFloat {
        return 120
        //searchBoxContainerView.frame.height
    }

```

**Comment by MarioIannotta** [comment]
Hi @Confidexuta 
you should use the method
`func addPullUpController(_ pullUpController: PullUpController, initialStickyPointOffset: CGFloat, animated: Bool)` and provide the "visible point height" as `initialStickyPointOffset`.

You can see how it's done in the example project.

**Comment by Confidexuta** [comment]
Thanks it works.
 But I have one new problem, how is it possible to remove the stickypoints, just like removing the whole bottomsheet when some action is triggered?
For example when I drag the bottomsheet to the last stickypoint, when I trigger some action it still stays there and new bottomsheet appears in the initial point.

**Comment by MarioIannotta** [comment]
What you need is the method `removePullUpController(_ pullUpController: PullUpController, animated: Bool)`
