### ISSUE TITLE
Expand and collapse programmatically?

### ISSUE THREAD

**Issue by AdAvAn** [MarioIannotta/PullUpController#43]
Good day.

Tell me whether it is possible to expand and collapse the PullUpController without using GestureRecognizer, but by exiting the methods expand(), collapse()?

**Comment by MarioIannotta** [comment]
From the docs:

It's possible to change the view controller's view position programmatically by using the method `pullUpControllerMoveToVisiblePoint(_ visiblePoint: CGFloat, animated: Bool, completion: (() -> Void)?)`
