### ISSUE TITLE
Сan't hide/show controller outside. 

### ISSUE THREAD

**Issue by Maxatma** [MarioIannotta/PullUpController#65]
As I understood documentation and code, you can only change pullupVC inside itself. However, there is a needs to hide/show it outside. 
I think there should be delegate for that, like in default UIKit  elements.

**Comment by MarioIannotta** [comment]
What do you mean with "you can only change pullupVC inside itself"? You can just reference is and call `addPullUpController` and `removePullUpController` wherever you want.

**Comment by Maxatma** [comment]
Hello. What if I don't want to remove it? I want to hide it down to initial point?
I want to use this, right? : 
        `pullpupController.pullUpControllerMoveToVisiblePoint(minimumPoint, animated: true, completion: nil)`

**Comment by MarioIannotta** [comment]
Yes, exactly.
And to show it again you can use the same method but with a different (>0) offset.

**Comment by Maxatma** [comment]
Okay, thanks.
