### ISSUE TITLE
Remove PullUpViewController Animation not working

### ISSUE THREAD

**Issue by SaluBhayo-zz** [MarioIannotta/PullUpController#69]
I have added a PullupController in a simple view controller added on UIButton click when I'm removing it through DidSelect Delegate of TableView in Pullup Controller view removed quickly without animation.

**Comment by MarioIannotta** [comment]
Hello there, it looks like an allocation issue; are you keeping a reference of the child controller? 
Can you reproduce the same issue on the demo example in this repository?

**Comment by SaluBhayo-zz** [comment]
Here is the code for PullupController's subclass

@MarioIannotta Edit: Please instead of pasting the whole code here attach an example project as a zip.
