### ISSUE TITLE
How to fix Contracted Height in PullUpController

### ISSUE THREAD

**Issue by 24purnima** [MarioIannotta/PullUpController#76]
Hey please find the video
I have some issues 
when I down the PullUpController it hides 
[RPReplay_Final1585292553.MP4.zip](https://github.com/MarioIannotta/PullUpController/files/4391989/RPReplay_Final1585292553.MP4.zip)

**Comment by 24purnima** [comment]
Hey please look into this I have an urgent requirement.

**Comment by MarioIannotta** [comment]
This looks like an issue with your code/storyboard.
Make sure all the sticky points are > 0
