### ISSUE TITLE
PullUpViewController Subviews Animate While Presenting

### ISSUE THREAD

**Issue by LeoSnek** [MarioIannotta/PullUpController#77]
I have an issue whereby my `PullUpViewController`'s subviews grow from left to right while it is expanding from the bottom: 

[PullUpVCBug.mp4.zip](https://github.com/MarioIannotta/PullUpController/files/4415429/PullUpVCBug.mp4.zip)

The red background is the `PullUpViewController.view` and the green is a `UIView` set up with the following constraints called from `viewDidLoad`:

    NSLayoutConstraint.activate([
        contentView.topAnchor.constraint(equalTo: view.topAnchor),
        contentView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
        contentView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
        contentView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
    ])

I'm sure it must be something simple but I nothing I have tried works.

**Comment by MarioIannotta** [comment]
Try adding a  `view.layoutIfNeeded()` after you setup the constraints. 
Also make sure `contentView.translatesAutoresizingMaskIntoConstraints` is `false`

**Comment by LeoSnek** [comment]
`view.layoutIfNeeded()` fixed it yep, thanks so much!
